views.query.avportal:
  type: views_query
  label: 'AV Portal query'
  mapping:
    cache_query_response:
      type: boolean
      label: 'Use cache for AV Portal queries response'

views.filter.avportal_text_search:
  type: views.filter.string
  label: 'AV Portal Full text Search'

views.filter.avportal_type_search:
  type: views.filter.in_operator
  label: 'AV Portal Type'

entity_browser.browser.widget.avportal_search:
  type: entity_browser.browser.widget.view
  label: 'AV Portal widget configuration'

entity_browser.browser.widget.av_portal_upload_link:
  type: mapping
  label: 'Widget configuration'
  mapping:
    submit_text:
      type: string
      label: 'Submit button text'

