media.source.oe_media_iframe:
  type: media.source.field_aware
  label: '"Video iframe" media source configuration'
  mapping:
    text_format:
      type: string
      label: 'Text format'

field.widget.settings.oe_media_iframe_textarea:
  type: mapping
  label: 'Textarea display format settings'
  mapping:
    rows:
      type: integer
      label: 'Rows'
    placeholder:
      type: label
      label: 'Placeholder'
